Configuration merge & update configuration defaults
gisat-panther/ptr-core pull request #14
Opened 2020-12-21 17:42 UTC by mbabic84

Merge configuration from environmental variables and from ssr preloaded state with application defaults given as parameter. Set default apiBackendPath option. Client has to be modified as bellow.

src/config/index.js

```
import _ from 'lodash';

import {config} from '@gisatcz/ptr-core';

/**
 * APP SPECIFIC DEFAULT VALUES
 */
import appDefaults from "./appDefaults";

export default config(appDefaults);
```

2021-04-27 07:05 UTC, vdubr requested changes

2021-04-27 07:05 UTC, vdubr commented on src/config/index.js
> +import _ from "lodash";
```import {each as _each, keys as _keys, merge as _merge} from 'lodash'```

2021-04-28 12:04 UTC, vdubr approved these changes

2021-04-28 13:08 UTC, vlach1989 approved these changes

2021-04-28 13:09 UTC, merged